### PR TITLE
Embed fargate data in container samples

### LINKED ISSUE #49: Docker integration should know when it's running in Fargate
## Description
When running in Fargate the ECS integration is not calling "connect" so all metadata related to the host is lost. Docker integration is also sending metrics without agent entityId. 

The result is that the metadata is not decorated and some attributes are lost:

- awsRegion
- ~ecsClusterName~
- ecsClusterArn
- ecsLaunchType

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen. )

## [NR Diag](https://docs.newrelic.com/docs/using-new-relic/cross-product-functions/troubleshooting/new-relic-diagnostics) results
[NOTE]: # ( Provide any other relevant log data. )
[TIP]:  # ( Scrub logs and diagnostic information for sensitive information )

## Steps to Reproduce
See initially filed tickets: https://newrelic.atlassian.net/browse/GTSE-4812
Aso solving: https://newrelic.atlassian.net/secure/RapidBoard.jspa?rapidView=1643&projectKey=GTSE&modal=detail&selectedIssue=GTSE-5145

## Your Environment
[TIP]:  # ( Include as many relevant details about your environment as possible including the running version of New Relic software and any relevant configurations. )

## Additional context
@jlegoff noticed the docker integration is using the same API used by the ECS integration and can detect if it is running inside Fargat

In case the Docker integration is running inside Fargate the integration will send those missing attributes as a metric attribute. For instance, the awsRegion is got from the ARN.

From @paologallinaharbur 
We should check that all the metadata is there from the old sample
[ODL](https://one.newrelic.com/launcher/nr1-core.explorer?pane=eyJuZXJkbGV0SWQiOiJlbnRpdHktb3ZlcnZpZXctbmVyZGxldHMuZWNzLWNsdXN0ZXItb3ZlcnZpZXctZGFzaGJvYXJkIiwiZW50aXR5SWQiOiJNVFUzTnpjeU0zeEpUa1pTUVh4T1FYdzJOekUwTmpVeU16WXhOakEyTnpZNE1EazIiLCJpc092ZXJ2aWV3Ijp0cnVlLCJyZWZlcnJlcnMiOnsibGF1bmNoZXJJZCI6Im5yMS1jb3JlLmV4cGxvcmVyIiwibmVyZGxldElkIjoibnIxLWNvcmUubGlzdGluZyJ9LCJyZWZyZXNoIjoxNjAyNTk4NjI3NzAwfQ==&overlay=eyJuZXJkbGV0SWQiOiJ3YW5kYS1kYXRhLWV4cGxvcmF0aW9uLmRhdGEtZXhwbG9yZXIiLCJpbml0aWFsQWN0aXZlSW50ZXJmYWNlIjoibnJxbEVkaXRvciIsImluaXRpYWxBY2NvdW50SWQiOjIzNzAzMTEsImluaXRpYWxOcnFsVmFsdWUiOiIiLCJpbml0aWFsUXVlcmllcyI6W3siYWNjb3VudElkIjoyMzcwMzExLCJucnFsIjoiRlJPTSBDb250YWluZXJTYW1wbGUgU0VMRUNUICogd2hlcmUgZWNzQ2x1c3Rlck5hbWUgPSAncHJkX2V1LXdlc3QtMV9jYWR0X2NvcmVfc2hkJyJ9XSwiaW5pdGlhbENoYXJ0U2V0dGluZ3MiOnsiY2hhcnRUeXBlIjoiQ0hBUlRfSlNPTiIsImxpbmtlZERhc2hib2FyZElkIjpudWxsfX0=&sidebars[0]=eyJuZXJkbGV0SWQiOiJucjEtY29yZS5hY3Rpb25zIiwiZW50aXR5SWQiOiJNVFUzTnpjeU0zeEpUa1pTUVh4T1FYdzJOekUwTmpVeU16WXhOakEyTnpZNE1EazIiLCJzZWxlY3RlZE5lcmRsZXQiOnsibmVyZGxldElkIjoiZW50aXR5LW92ZXJ2aWV3LW5lcmRsZXRzLmVjcy1jbHVzdGVyLW92ZXJ2aWV3LWRhc2hib2FyZCIsImlzT3ZlcnZpZXciOnRydWV9fQ==&platform[timeRange][duration]=259200000&platform[filters]=IihuYW1lIGxpa2UgJ2FsbG9jYXRpb24tbG9jYXRpb24nIG9yIGlkID0gJ2FsbG9jYXRpb24tbG9jYXRpb24nIG9yIGRvbWFpbklkID0gJ2FsbG9jYXRpb24tbG9jYXRpb24nKSI=), [NEW](https://one.newrelic.com/launcher/nr1-core.explorer?pane=eyJuZXJkbGV0SWQiOiJlbnRpdHktb3ZlcnZpZXctbmVyZGxldHMuZWNzLWNsdXN0ZXItb3ZlcnZpZXctZGFzaGJvYXJkIiwiZW50aXR5SWQiOiJNVFUzTnpjeU0zeEpUa1pTUVh4T1FYdzJOekUwTmpVeU16WXhOakEyTnpZNE1EazIiLCJpc092ZXJ2aWV3Ijp0cnVlLCJyZWZlcnJlcnMiOnsibGF1bmNoZXJJZCI6Im5yMS1jb3JlLmV4cGxvcmVyIiwibmVyZGxldElkIjoibnIxLWNvcmUubGlzdGluZyJ9LCJyZWZyZXNoIjoxNjAyNTk4NzM3ODUzfQ==&overlay=eyJpbml0aWFsQWN0aXZlSW50ZXJmYWNlIjoibnJxbEVkaXRvciIsImluaXRpYWxRdWVyaWVzIjpbeyJhY2NvdW50SWQiOjE1Nzc3MjMsIm5ycWwiOiJGUk9NIENvbnRhaW5lclNhbXBsZSBTRUxFQ1QgKiBXSEVSRSBlY3NDbHVzdGVyTmFtZSA9ICdkZXYtZXUtd2VzdC0xLWFsbG9jYXRpb24tY29yZScgICJ9XSwiaW5pdGlhbENoYXJ0VHlwZSI6ImJpbGxib2FyZCIsImVkaXRNb2RlIjoiVklFVyIsInRpbWVSYW5nZSI6eyJkdXJhdGlvbiI6MjU5MjAwMDAwLCJiZWdpbl90aW1lIjpudWxsLCJlbmRfdGltZSI6bnVsbH0sIm5lcmRsZXRJZCI6IndhbmRhLWRhdGEtZXhwbG9yYXRpb24uZGF0YS1leHBsb3JlciIsImluaXRpYWxOcnFsVmFsdWUiOiIiLCJpbml0aWFsQWNjb3VudElkIjoxNTc3NzIzLCJpbml0aWFsQ2hhcnRTZXR0aW5ncyI6eyJjaGFydFR5cGUiOiJDSEFSVF9KU09OIiwibGlua2VkRGFzaGJvYXJkSWQiOm51bGx9LCJpbml0aWFsVGltZVdpbmRvd092ZXJyaWRlIjpudWxsfQ==&sidebars[0]=eyJuZXJkbGV0SWQiOiJucjEtY29yZS5hY3Rpb25zIiwiZW50aXR5SWQiOiJNVFUzTnpjeU0zeEpUa1pTUVh4T1FYdzJOekUwTmpVeU16WXhOakEyTnpZNE1EazIiLCJzZWxlY3RlZE5lcmRsZXQiOnsibmVyZGxldElkIjoiZW50aXR5LW92ZXJ2aWV3LW5lcmRsZXRzLmVjcy1jbHVzdGVyLW92ZXJ2aWV3LWRhc2hib2FyZCIsImlzT3ZlcnZpZXciOnRydWV9fQ==&platform[timeRange][duration]=259200000&platform[filters]=IihuYW1lIGxpa2UgJ2FsbG9jYXRpb24tbG9jYXRpb24nIG9yIGlkID0gJ2FsbG9jYXRpb24tbG9jYXRpb24nIG9yIGRvbWFpbklkID0gJ2FsbG9jYXRpb24tbG9jYXRpb24nKSI=)

https://github.com/newrelic/nri-ecs/blob/e2b3668bb8b244eda85ce113abac3d2e41251834/internal/metadata/v3/v3.go#L165

https://github.com/newrelic/nri-docker/blob/master/src/docker.go#L47

impersonate - See comments in [CoreINT-337](https://newrelic.atlassian.net/browse/COREINT-337)

### PR DESCRIPTION
**Pull request by roobre**
Fixes #49 

When running in transparent mode, as is the case in Fargate, the agent will not decorate metrics with Fargate metadata such as `awsRegion`, `ecsLaunchType`, and `ecsClusterName`. Breaking queries that use such attributes.

In this PR we fix this by pulling such metadata from the docker container labels that Fargate adds to the container information, by parsing the task arn and the cluster name. This is the same way in which https://github.com/newrelic/nri-ecs obtains this information. `RegionFromTask` and `ResourceNameAndARNBase` have been pulled from said repo as well.

### TODO:

- [x] Unit testing

### Manual testing checklist

- [x] Integration works as expected in Fargate mode, when `FARGATE` and `NRIA_IS_FORWARD_ONLY` are set
- [x] Integration works in as expected in EC2 mode
[json-comparison.tar.gz](https://github.com/newrelic/nri-docker/files/5517495/json-comparison.tar.gz)

### CODE REVIEW

**Comment by roobre** [comment]
Tests fail for b102213aea3845414baf58c631070920bb4cf363 since test data does not conform to the format defined by AWS.

File: src/raw/aws/fargate_inspector.go [hunk 1]
```diff
@@ -129,10 +129,24 @@ func containerResponseToDocker(container ContainerResponse) types.Container {
...
-		// Meanwhile, in ECS with Fargate launch type the same label has the full cluster ARN as value.
-		if label == "com.amazonaws.ecs.cluster" && isECSARN(value) {
-			labels[label] = ecsClusterNameFromARN(value)
+		switch label {
+		case "com.amazonaws.ecs.cluster":
+			if isECSARN(value) {
+				// The cluster name label has to be processed because in ECS with EC2 launch type it's only the cluster name.
+				// Meanwhile, in ECS with Fargate launch type the same label has the full cluster ARN as value.
+				labels[label] = ecsClusterNameFromARN(value)
+				// preserve the original arn is preserved in the following synthetic label
```
Comment (roobre) [inline src/raw/aws/fargate_inspector.go:138]: Derp wording

File: src/raw/aws/fargate_inspector.go [hunk 2]
```diff
@@ -129,10 +129,24 @@ func containerResponseToDocker(container ContainerResponse) types.Container {
...
+				labels["com.newrelic.nri-docker.cluster-arn"] = value
+				// Add label signaling fargate launch type
+				labels["com.newrelic.nri-docker.launch-type"] = "fargate"
```
Comment (roobre) [inline src/raw/aws/fargate_inspector.go:141]: `launchType` will be set to `fargate` if the `com.amazonaws.ecs.cluster` label has an ARN format. This is somehow a "weak" indicator of whether we are running in Fargate or not.

If we can guarantee that the agent/backend will override this setting, we should be fine with this.

**Review by gsanchezgavier — APPROVED** [review]
looks good thanks for adding the test

File: src/raw/aws/fargate_inspector.go [hunk 3]
```diff
@@ -153,3 +168,19 @@ func isECSARN(arn string) bool {
...
+// Example of task ARN: arn:aws:ecs:us-west-2:xxxxxxxx:task/ecs-local-cluster/37e873f6-37b4-42a7-af47-eac7275c6152
+func regionFromTask(taskARN string) string {
+	_, arnPrefix := resourceNameAndARNBase(taskARN)
+	return strings.Split(arnPrefix, ":")[3]
+}
+
+// resourceNameAndARNBase explodes a resource ARN and returns the resource's name and the base ARN prefix for the
+// account and region of the original resource.
+func resourceNameAndARNBase(resourceARN string) (resourceName string, arnPrefix string) {
+	arnPrefixAndType := resourceARN[:strings.Index(resourceARN, "/")-1]
```
Comment (paologallinaharbur) [inline src/raw/aws/fargate_inspector.go:182]: Can we use the strings.Split function instead? 
Only to avoid splitting and using indexes directly

**Review by paologallinaharbur — APPROVED** [review]
Only a small comments, I believe it is fine, but if we can I would use the standard function 👍 
Well done!

File: src/raw/aws/fargate_inspector.go (hunk 3 above)
Comment (roobre) [reply src/raw/aws/fargate_inspector.go:182]: Both functions were taken (i.e. copy-pasted) from [nri-ecs](https://github.com/newrelic/nri-ecs/blob/main/internal/metadata/v3/v3.go), and were left untouched for consistency even when I do not particularly like the implementation of either. The one that uses split, for example, does not perform any kind of bound-checking and relies on the passed string to be an arn.

If we are ok with changing them, I'd vote for rewriting both of them to use `strings.Split` and proper bound checking. What do you think?

File: src/raw/aws/fargate_inspector.go (hunk 2 above)
Comment (roobre) [reply src/raw/aws/fargate_inspector.go:141]: On secondary inspection, I found out that this is actually cannot happen, since far label processing is done only when the `FARGATE` env is set.

**Comment by roobre** [comment]
Following a conversation with @paologallinaharbur, we decided that the best approach for now would be to include the aws sdk even for this tiny bit (arn parsing), and file an issue to switch to said SDK for everything else (hopefully removing all manually vendored files)

**Review by gsanchezgavier — APPROVED** [review]
